language: generic
sudo: required
services:
    - docker
before_install:
    docker build -t yshoang/docker-react -f Dockerfile.dev .
script:
    docker run -e CI=true yshoang/docker-react npm run test
     
deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "Docker-react-env" 
    skip_cleanup: true
    bucket_name: "elasticbeanstalk-us-east-1-076104269186"
    bucket_path: "docker-react"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_KEY

    