language: generic
sudo: required
services:
    - docker
before_install:
    docker build -t yshoang/docker-react -f Dockerfile.dev .
script:
    docker run -e CI=true yshoang/docker-react npm run test
     
deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-1"
    app: "docker-react"
    env: "DocekerReact-env"
    bucket_name: "arn:aws:s3:::elasticbeanstalk-ap-southeast-1-245933506054"
    bucket_path: "docker-react"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_key_id: $AWS_SECRET_KEY