version: '3'

services: 
    web: 
        stdin_open: true
        build: 
            context: .
            dockerfile: Dockerfile.dev
            args: 
                buildno: 1
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app